<?php

namespace Database\Seeders;

use App\Models\Medication;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MedicationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $medications = [
            [
                'medication_name' => 'アムロジピンOD錠5mg',
                'dosage' => '5mg',
                'notes' => '高血圧症や狭心症の治療に使われるお薬です。水なしで飲める口腔内崩壊錠。',
                'effect' => '高血圧症、狭心症の治療',
                'side_effects' => '顔のほてり、頭痛、動悸、めまい',
            ],
            [
                'medication_name' => 'メトグルコ錠500mg',
                'dosage' => '500mg',
                'notes' => '2型糖尿病の治療に使われる血糖値を下げるお薬です。消化器症状が出やすい場合があります。',
                'effect' => '2型糖尿病の治療（血糖降下）',
                'side_effects' => '下痢、悪心、食欲不振',
            ],
            [
                'medication_name' => 'ロキソプロフェンNa錠60mg',
                'dosage' => '60mg',
                'notes' => '痛みや熱を抑える、一般的な解熱鎮痛薬です。空腹時の服用は胃に負担をかけることがあります。',
                'effect' => '解熱、鎮痛、抗炎症',
                'side_effects' => '胃部不快感、腹痛',
            ],
            [
                'medication_name' => 'ガスモチン錠5mg',
                'dosage' => '5mg',
                'notes' => '胃や腸の動きを助ける消化管運動改善薬です。食欲不振や胃もたれに効果的です。',
                'effect' => '消化管運動機能改善',
                'side_effects' => '腹部膨満感、吐き気',
            ],
            [
                'medication_name' => 'ビオフェルミン錠剤',
                'dosage' => '1錠',
                'notes' => '腸内環境を整える乳酸菌が主成分の整腸剤です。',
                'effect' => '整腸、便秘、軟便',
                'side_effects' => null,
            ],
            [
                'medication_name' => 'プレドニン錠5mg',
                'dosage' => '5mg',
                'notes' => '炎症やアレルギーを抑えるステロイド性のお薬です。長期服用で副作用が出やすいため、医師の指示を厳守してください。',
                'effect' => 'アレルギー疾患、膠原病、炎症性疾患',
                'side_effects' => 'ムーンフェイス、骨粗しょう症、感染症',
            ],
            [
                'medication_name' => 'セロクエル錠25mg',
                'dosage' => '25mg',
                'notes' => '心のバランスを整える精神疾患治療薬です。服用初期に強い眠気を感じることがあります。',
                'effect' => '統合失調症、双極性障害',
                'side_effects' => '眠気、めまい、口渇',
            ],
            [
                'medication_name' => 'アレグラ錠60mg',
                'dosage' => '60mg',
                'notes' => 'アレルギー症状を和らげる抗ヒスタミン薬です。一般的な抗ヒスタミン薬に比べて眠気が出にくい特徴があります。',
                'effect' => 'アレルギー性鼻炎、蕁麻疹',
                'side_effects' => '眠気が少ない',
            ],
            [
                'medication_name' => 'ラシックス錠20mg',
                'dosage' => '20mg',
                'notes' => '体内の余分な水分を排出する利尿作用があるお薬です。服用後、頻繁に排尿を催すことがあります。',
                'effect' => '高血圧症、心性浮腫、腎性浮腫',
                'side_effects' => '脱水、低カリウム血症',
            ],
            [
                'medication_name' => 'タケキャブ錠10mg',
                'dosage' => '10mg',
                'notes' => '胃酸の分泌を強力に抑える胃潰瘍・逆流性食道炎治療薬です。',
                'effect' => '胃潰瘍、逆流性食道炎',
                'side_effects' => '便秘、下痢',
            ],
            [
                'medication_name' => 'バイアスピリン錠100mg',
                'dosage' => '100mg',
                'notes' => '血をサラサラにする薬です。脳梗塞や心筋梗塞の再発予防に用いられます。',
                'effect' => '血栓・塞栓形成の抑制',
                'side_effects' => '胃腸障害、出血傾向',
            ],
            [
                'medication_name' => 'クレストール錠2.5mg',
                'dosage' => '2.5mg',
                'notes' => 'コレステロール値を下げる高脂血症治療薬です。',
                'effect' => '高コレステロール血症の治療',
                'side_effects' => '肝機能障害、筋肉痛',
            ],
            [
                'medication_name' => 'ワーファリン錠1mg',
                'dosage' => '1mg',
                'notes' => '血液を固まりにくくする抗凝固薬です。納豆などビタミンKを多く含む食品に注意。',
                'effect' => '血栓塞栓症の治療・予防',
                'side_effects' => '出血',
            ],
            [
                'medication_name' => 'ムコスタ錠100mg',
                'dosage' => '100mg',
                'notes' => '胃の粘膜を保護し、胃炎や胃潰瘍を改善する薬です。',
                'effect' => '胃炎、胃潰瘍の治療',
                'side_effects' => '口渇、便秘、下痢',
            ],
            [
                'medication_name' => 'リリカカプセル75mg',
                'dosage' => '75mg',
                'notes' => '神経の興奮を抑え、痛みを和らげる神経障害性疼痛治療薬です。',
                'effect' => '神経障害性疼痛、線維筋痛症の治療',
                'side_effects' => 'めまい、眠気',
            ],
            [
                'medication_name' => 'デパス錠0.5mg',
                'dosage' => '0.5mg',
                'notes' => '不安や緊張を和らげる抗不安薬です。依存性に注意が必要です。',
                'effect' => '神経症における不安・緊張・抑うつ',
                'side_effects' => '眠気、ふらつき、口渇',
            ],
            [
                'medication_name' => 'セフジニルカプセル100mg',
                'dosage' => '100mg',
                'notes' => '細菌感染症の治療に使われる抗生物質です。',
                'effect' => '各種細菌感染症の治療',
                'side_effects' => '下痢、発疹',
            ],
            [
                'medication_name' => 'カロナール錠200mg',
                'dosage' => '200mg',
                'notes' => '一般的な痛みや発熱を和らげる薬です。',
                'effect' => '解熱、鎮痛',
                'side_effects' => '吐き気、食欲不振',
            ],
            [
                'medication_name' => 'ビタミンB群剤',
                'dosage' => '1錠',
                'notes' => 'ビタミンB群を補給する総合ビタミン剤です。',
                'effect' => 'ビタミンB群欠乏症の予防・治療',
                'side_effects' => null,
            ],
            [
                'medication_name' => 'マグミット錠250mg',
                'dosage' => '250mg',
                'notes' => '便をやわらかくする便秘薬です。水と一緒に多めに服用してください。',
                'effect' => '便秘症の治療',
                'side_effects' => '下痢',
            ],
            [
                'medication_name' => 'ダイアップ坐剤4mg',
                'dosage' => '4mg',
                'notes' => '熱性けいれんやてんかんのけいれんを止める坐剤です。',
                'effect' => 'けいれんの抑制',
                'side_effects' => '眠気',
            ],
            [
                'medication_name' => 'シングレア錠10mg',
                'dosage' => '10mg',
                'notes' => '気管支喘息やアレルギー性鼻炎の症状を抑える薬です。',
                'effect' => '気管支喘息、アレルギー性鼻炎の治療',
                'side_effects' => '頭痛、腹痛',
            ],
            [
                'medication_name' => 'ネキシウムカプセル20mg',
                'dosage' => '20mg',
                'notes' => '胃酸の分泌を強力に抑えるPPI（プロトンポンプ阻害薬）です。',
                'effect' => '胃潰瘍、逆流性食道炎',
                'side_effects' => '下痢、便秘',
            ],
            [
                'medication_name' => 'ミヤBM細粒',
                'dosage' => '1g',
                'notes' => '腸内の善玉菌を増やし、腸内環境を整える整腸剤です。',
                'effect' => '整腸、便秘、軟便',
                'side_effects' => null,
            ],
            [
                'medication_name' => '葛根湯エキス顆粒',
                'dosage' => '1包',
                'notes' => '風邪のひき始めや肩こりに効果的な漢方薬です。',
                'effect' => '感冒、肩こり',
                'side_effects' => '胃部不快感',
            ],
            [
                'medication_name' => 'リクシアナ錠30mg',
                'dosage' => '30mg',
                'notes' => '心房細動における脳卒中・全身性塞栓症の発症抑制に用いられる抗凝固薬です。',
                'effect' => '血栓症の治療・予防',
                'side_effects' => '出血',
            ],
            [
                'medication_name' => 'エパデールS300',
                'dosage' => '300mg',
                'notes' => '血液中のコレステロールや中性脂肪を減らす薬です。',
                'effect' => '高脂血症の治療',
                'side_effects' => '発疹、かゆみ',
            ],
            [
                'medication_name' => 'ビソプロロールフマル酸塩錠5mg',
                'dosage' => '5mg',
                'notes' => '高血圧症や不整脈、狭心症、慢性心不全の治療に使われるβ遮断薬です。',
                'effect' => '高血圧症、不整脈、狭心症、慢性心不全',
                'side_effects' => '徐脈、めまい',
            ],
            [
                'medication_name' => 'ラベプラゾールNa錠10mg',
                'dosage' => '10mg',
                'notes' => '胃酸の分泌を抑えるPPI（プロトンポンプ阻害薬）です。',
                'effect' => '胃潰瘍、逆流性食道炎',
                'side_effects' => '下痢、便秘',
            ],
            [
                'medication_name' => 'セレスタミン配合錠',
                'dosage' => '1錠',
                'notes' => 'アレルギー症状や炎症を強力に抑えるステロイドと抗ヒスタミン薬の配合剤です。',
                'effect' => 'アレルギー性疾患、蕁麻疹',
                'side_effects' => '眠気、口渇',
            ],
            [
                'medication_name' => 'テルネリン錠1mg',
                'dosage' => '1mg',
                'notes' => '筋肉の緊張を和らげる筋弛緩薬です。',
                'effect' => '痙性麻痺、筋骨格系疾患による痙性',
                'side_effects' => '眠気、口渇',
            ],
            [
                'medication_name' => 'トラムセット配合錠',
                'dosage' => '1錠',
                'notes' => '強い痛みを抑える鎮痛薬です。非オピオイド系鎮痛薬とオピオイド系鎮痛薬の配合剤。',
                'effect' => '非がん性慢性疼痛、抜歯後疼痛',
                'side_effects' => '吐き気、便秘、眠気',
            ],
            [
                'medication_name' => 'ザイロリック錠100mg',
                'dosage' => '100mg',
                'notes' => '尿酸の生成を抑えることで痛風発作を予防する薬です。',
                'effect' => '痛風、高尿酸血症',
                'side_effects' => '発疹、肝機能障害',
            ],
            [
                'medication_name' => 'アジルバ錠20mg',
                'dosage' => '20mg',
                'notes' => '高血圧症の治療に使われるアンジオテンシンII受容体拮抗薬（ARB）です。',
                'effect' => '高血圧症',
                'side_effects' => 'めまい、頭痛',
            ],
            [
                'medication_name' => 'フェロミア錠50mg',
                'dosage' => '50mg',
                'notes' => '鉄分を補給して貧血を改善する鉄剤です。',
                'effect' => '鉄欠乏性貧血',
                'side_effects' => '吐き気、腹痛、便秘、下痢',
            ],
            [
                'medication_name' => 'レクサプロ錠10mg',
                'dosage' => '10mg',
                'notes' => 'うつ病や社会不安障害の治療に使われる抗うつ薬です。',
                'effect' => 'うつ病、社会不安障害',
                'side_effects' => '吐き気、眠気、性機能障害',
            ],
            [
                'medication_name' => 'ムコダイン錠500mg',
                'dosage' => '500mg',
                'notes' => '痰を出しやすくする去痰剤です。',
                'effect' => '喀痰喀出困難、副鼻腔炎の排膿',
                'side_effects' => '胃部不快感、食欲不振',
            ],
            [
                'medication_name' => 'シングリックス筋注用',
                'dosage' => '1回',
                'notes' => '帯状疱疹を予防するためのワクチンです。2回接種。',
                'effect' => '帯状疱疹の予防',
                'side_effects' => '注射部位の痛み、腫れ、発赤',
            ],
            [
                'medication_name' => 'タミフルカプセル75mg',
                'dosage' => '75mg',
                'notes' => 'インフルエンザウイルスの増殖を抑える抗インフルエンザウイルス薬です。',
                'effect' => 'インフルエンザウイルス感染症の治療・予防',
                'side_effects' => '腹痛、下痢、悪心',
            ],
            [
                'medication_name' => 'リフレックス錠15mg',
                'dosage' => '15mg',
                'notes' => 'うつ病の治療に使われる抗うつ薬です。眠気が出やすいことがあります。',
                'effect' => 'うつ病・うつ状態',
                'side_effects' => '眠気、口渇、体重増加',
            ],
            [
                'medication_name' => 'ミカルディス錠40mg',
                'dosage' => '40mg',
                'notes' => '高血圧症の治療に使われるアンジオテンシンII受容体拮抗薬（ARB）です。',
                'effect' => '高血圧症',
                'side_effects' => 'めまい、頭痛',
            ],
            [
                'medication_name' => 'デノタスチュアブル錠',
                'dosage' => '1錠',
                'notes' => '高リン血症の治療薬です。噛み砕いて服用します。',
                'effect' => '慢性腎臓病患者における高リン血症の改善',
                'side_effects' => '便秘、下痢',
            ],
            [
                'medication_name' => 'ウルソ錠100mg',
                'dosage' => '100mg',
                'notes' => '肝機能を改善する薬です。',
                'effect' => '肝機能改善、胆汁うっ滞の改善',
                'side_effects' => '下痢',
            ],
            [
                'medication_name' => 'ドグマチール錠50mg',
                'dosage' => '50mg',
                'notes' => 'うつ病、胃・十二指腸潰瘍、吐き気などに使われる薬です。',
                'effect' => 'うつ病、胃・十二指腸潰瘍、悪心・嘔吐',
                'side_effects' => '眠気、乳汁分泌、月経異常',
            ],
            [
                'medication_name' => 'イブプロフェン錠100mg',
                'dosage' => '100mg',
                'notes' => '熱や痛みを抑える一般的な解熱鎮痛薬です。',
                'effect' => '解熱、鎮痛',
                'side_effects' => '胃部不快感',
            ],
            [
                'medication_name' => 'リベルサス錠7mg',
                'dosage' => '7mg',
                'notes' => '2型糖尿病の治療に使われる経口GLP-1受容体作動薬です。空腹時に服用。',
                'effect' => '2型糖尿病',
                'side_effects' => '吐き気、下痢',
            ],
            [
                'medication_name' => 'エビリファイ錠3mg',
                'dosage' => '3mg',
                'notes' => '統合失調症や双極性障害の治療に使われる抗精神病薬です。',
                'effect' => '統合失調症、双極性障害',
                'side_effects' => 'アカシジア、眠気',
            ],
            [
                'medication_name' => 'カログラ錠20mg',
                'dosage' => '20mg',
                'notes' => 'アレルギー性鼻炎や皮膚炎の治療に使われる抗アレルギー薬です。',
                'effect' => 'アレルギー性鼻炎、蕁麻疹、皮膚炎',
                'side_effects' => '眠気、口渇',
            ],
            [
                'medication_name' => 'エディロールカプセル0.75μg',
                'dosage' => '0.75μg',
                'notes' => '骨粗しょう症の治療に使われる活性型ビタミンD3製剤です。',
                'effect' => '骨粗しょう症',
                'side_effects' => '高カルシウム血症',
            ],
            [
                'medication_name' => 'アリセプト錠5mg',
                'dosage' => '5mg',
                'notes' => 'アルツハイマー型認知症の進行を抑える薬です。',
                'effect' => 'アルツハイマー型認知症',
                'side_effects' => '吐き気、下痢、食欲不振',
            ],
            [
                'medication_name' => 'サインバルタカプセル20mg',
                'dosage' => '20mg',
                'notes' => 'うつ病や様々な痛みに使われるSNRI（セロトニン・ノルアドレナリン再取り込み阻害薬）です。',
                'effect' => 'うつ病、慢性疼痛',
                'side_effects' => '吐き気、眠気、口渇',
            ],
            [
                'medication_name' => 'ガスターD錠20mg',
                'dosage' => '20mg',
                'notes' => '胃酸の分泌を抑えるH2ブロッカーです。',
                'effect' => '胃潰瘍、逆流性食道炎',
                'side_effects' => '便秘、下痢',
            ],
            [
                'medication_name' => 'ベタヒスチンメシル酸塩錠6mg',
                'dosage' => '6mg',
                'notes' => 'めまいや耳鳴りの症状を改善する薬です。',
                'effect' => 'メニエール病、めまい、耳鳴り',
                'side_effects' => '吐き気、食欲不振',
            ],
            [
                'medication_name' => 'アモキシシリンカプセル250mg',
                'dosage' => '250mg',
                'notes' => '細菌感染症に使われるペニシリン系の抗生物質です。',
                'effect' => '各種細菌感染症',
                'side_effects' => '下痢、発疹',
            ],
            [
                'medication_name' => 'モンテルカスト錠10mg',
                'dosage' => '10mg',
                'notes' => '気管支喘息やアレルギー性鼻炎の症状を抑える薬です。',
                'effect' => '気管支喘息、アレルギー性鼻炎',
                'side_effects' => '頭痛、腹痛',
            ],
            [
                'medication_name' => 'レバミピド錠100mg',
                'dosage' => '100mg',
                'notes' => '胃の粘膜を保護し、胃炎や胃潰瘍を改善する薬です。',
                'effect' => '胃潰瘍、胃粘膜病変の改善',
                'side_effects' => '便秘、口渇',
            ],
            [
                'medication_name' => 'エチゾラム錠0.5mg',
                'dosage' => '0.5mg',
                'notes' => '不安や不眠の症状を和らげる薬です。依存性に注意が必要。',
                'effect' => '神経症、心身症における不安・緊張・抑うつ、不眠症',
                'side_effects' => '眠気、ふらつき',
            ],
            [
                'medication_name' => 'フルイトラン錠1mg',
                'dosage' => '1mg',
                'notes' => '体内の余分な水分を排出する利尿薬です。',
                'effect' => '高血圧症、浮腫',
                'side_effects' => '低カリウム血症、脱水',
            ],
            [
                'medication_name' => 'ロゼレム錠8mg',
                'dosage' => '8mg',
                'notes' => '不眠症の治療に使われる睡眠導入剤です。自然な眠気を誘います。',
                'effect' => '不眠症（入眠困難）',
                'side_effects' => '傾眠、頭痛',
            ],
            [
                'medication_name' => 'タクロリムスカプセル1mg',
                'dosage' => '1mg',
                'notes' => '臓器移植後の拒絶反応抑制や、自己免疫疾患の治療に使われる免疫抑制剤です。',
                'effect' => '臓器移植後の拒絶反応抑制、重症筋無力症など',
                'side_effects' => '腎機能障害、糖尿病',
            ],
        ];

        foreach ($medications as $medicationData) {
            if (Medication::where('medication_name', $medicationData['medication_name'])->doesntExist()) {
                Medication::create($medicationData);
            }
        }
    }
}